import { Metadata } from "next"

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by Next.js',
}

export default async function Blog() {
  await new Promise((resolve) => {
    setTimeout(() => {
      resolve("intentional delay")
    }, 2000)
  })
  return <h1>Blog</h1>
}